# name of the job
name: Compile oled

# specify which paths to watch for changes
on:
  push:
    paths:
      - 'examples/oled/*'
      - .github/workflows/compile.yaml
      - .github/workflows/compile-oled.yaml

# run compile via the compile.yaml
jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        # CHANGE program/lib/aux as needed
        program:
          - name: 'oled'
            src: 'examples/oled'
            lib: 'Adafruit_SSD1306_RK Adafruit_GFX_RK Adafruit_BusIO_RK'
            aux: ''
        # CHANGE platforms as needed
        platform: 
          - {name: 'p2', version: '6.3.2'}

    # program name
    name: ${{ matrix.program.name }}-${{ matrix.platform.name }}-${{ matrix.platform.version }}

    # workflow call
    uses: ./.github/workflows/compile.yaml
    secrets: inherit
    with:
      program: ${{ matrix.program.name }}
      platform: ${{ matrix.platform.name }}
      version: ${{ matrix.platform.version }}      
      src: ${{ matrix.program.src }}
      lib: ${{ matrix.program.lib }}
      aux: ${{ matrix.program.aux }}