name: Compile Firmware

on:
  workflow_dispatch:  
  push:
    paths:
      - test/**
      - .github/workflows/compile.yaml

jobs:
  compile:
    runs-on: ubuntu-latest

    name: ${{ matrix.program.src }}-${{ matrix.platform.name }}-${{ matrix.platform.version }}

    strategy:
      fail-fast: false
      matrix:
        platform: 
          - {name: 'p2', version: '6.3.2'}
#          - {name: 'argon', version: '4.2.0'}
#          - {name: 'photon', version: '2.3.1'}
        root:
          - 'test'
        program:
          - src: 'blink'
            lib: 'DeviceNameHelperRK MyLib'
          - src: 'publish'
            lib: 'DeviceNameHelperRK FileHelperRK SequentialFileRK PublishQueueExtRK SparkFun_Qwiic_OpenLog_Arduino_Library'
            other: 'LoggerCore/src/LoggerPlatform* LoggerCore/src/LoggerUtils* LoggerCore/src/LoggerPublisher* LoggerCore/src/LoggerSD*'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive 

      - name: Gather application sources 
        run: |
          echo "Creating temporary source directory"
          mkdir ${{ matrix.program.src }}
          echo "Including sources from ${{ matrix.root }}/${{ matrix.program.src }}"
          mv ${{ matrix.root }}/${{ matrix.program.src }}/* ${{ matrix.program.src }} 

      - name: Gather application libraries
        if: contains(${{ matrix.program }}, 'lib')
        run: |
          echo "Including libraries:"
          for lib in ${{ matrix.program.lib }}; do
            echo " - lib/$(lib)/src/*"
            mv lib/$(lib)/src/* ${{ matrix.program.src }}
          done

      - name: Gather other application resources
        if: contains(${{ matrix.program }}, 'other')
        run: |
          echo "Including other resources:"
          for other in ${{ matrix.program.other }}; do
            echo " - $other"
            mv $other ${{ matrix.program.src }}
          done

      - name: Compile in cloud
        id: compile
        uses: particle-iot/compile-action@v1
        with:
          particle-access-token: ${{ secrets.PARTICLE_ACCESS_TOKEN }}
          particle-platform-name: ${{ matrix.platform.name }}
          device-os-version: ${{ matrix.platform.version }}
          sources-folder: ${{ matrix.program.src }}

      - name: Move binary
        run: |
          mv ${{ steps.compile.outputs.firmware-path }} ${{ matrix.program.src }}/${{ matrix.program.src }}-${{ matrix.platform.name }}-${{ matrix.platform.version }}.bin

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.program.src }}-${{ matrix.platform.name }}-${{ matrix.platform.version }}
          path: ${{ matrix.program.src }}

      - name: Compile locally to debug
        if: ${{ failure() }}
        uses: particle-iot/compile-action@v1
        with:
          particle-platform-name: ${{ matrix.platform.name }}
          device-os-version: ${{ matrix.platform.version }}
          sources-folder: ${{ matrix.program.src }}