name: Base workflow for compile

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      version:
        required: true
        type: string
      src:
        required: true
        type: string
      lib:
        required: false
        type: string
      aux:
        required: false
        type: string


jobs:
  compile:
    runs-on: ubuntu-latest

    name: ${{ inputs.src }}-${{ inputs.platform }}-${{ inputs.version }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive 

      - name: Gather application sources 
        run: |
          echo "Creating temporary source directory"
          mkdir ${{ inputs.src }}
          echo "Including sources from src/${{ inputs.src }}"
          mv src/${{ inputs.src }}/* ${{ inputs.src }} 
          echo "Including libraries:"
          for lib in ${{ inputs.lib }}; do
            if [ -d "$lib" ]; then
              echo " - $lib/*"
              mv $lib/* ${{ inputs.src }}
            elif [ -d "lib/$lib" ]; then
              echo " - lib/$lib/*"
              mv lib/$lib/* ${{ inputs.src }}
            else
              echo " - could not find $lib, make sure the folder exists"
            fi
          done
          echo "Including auxiliary resources:"
          for aux in ${{ inputs.aux }}; do
            echo " - $aux"
            mv $aux ${{ inputs.src }}
          done

      - name: Compile in cloud (on master)
        if: ${{ github.ref == 'refs/heads/master' }}
        id: compile
        uses: particle-iot/compile-action@v1
        with:
          particle-access-token: ${{ secrets.PARTICLE_ACCESS_TOKEN }}
          particle-platform-name: ${{ inputs.platform }}
          device-os-version: ${{ inputs.version }}
          sources-folder: ${{ inputs.src }}

      - name: Move cloud binary
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          mv ${{ steps.compile.outputs.firmware-path }} ${{ inputs.src }}/${{ inputs.src }}-${{ inputs.platform }}-${{ inputs.version }}.bin

      - name: Compile locally # if not on master or if cloud compile failed
        if: ${{ failure() || github.ref != 'refs/heads/master' }}
        id: localcompile
        uses: particle-iot/compile-action@v1
        with:
          particle-platform-name: ${{ inputs.platform }}
          device-os-version: ${{ inputs.version }}
          sources-folder: ${{ inputs.src }}

      - name: Move local binary
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          mv ${{ steps.localcompile.outputs.firmware-path }} ${{ inputs.src }}/${{ inputs.src }}-${{ inputs.platform }}-${{ inputs.version }}.bin

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.src }}-${{ inputs.platform }}-${{ inputs.version }}
          path: ${{ inputs.src }}
