# name of the job
name: Compile controller

# specify which paths to watch for changes
on:
  push:
    paths:
      - src/controller
      - LoggerCore/src
      - .github/workflows/compile.yaml
      - .github/workflows/compile-controller.yaml

# run compile via the compile.yaml
jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        # CHANGE program/lib/aux as needed
        program:
          - src: 'controller'
            lib: 'LoggerCore DeviceNameHelperRK FileHelperRK SequentialFileRK PublishQueueExtRK SparkFun_Qwiic_OpenLog_Arduino_Library'
            aux: ''
        # CHANGE platforms as needed
        platform: 
          - {name: 'photon2', version: '6.3.2'}

    # program name
    name: ${{ matrix.program.src }}-${{ matrix.platform.name }}-${{ matrix.platform.version }}

    # workflow call
    uses: ./.github/workflows/compile.yaml
    with:
      platform: ${{ matrix.platform.name }}
      version: ${{ matrix.platform.version }}
      src: ${{ matrix.program.src }}
      lib: ${{ matrix.program.lib }}
      aux: ${{ matrix.program.aux }}