name: Compile Firmware

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      version:
        required: true
        type: string
      src:
        required: true
        type: string
      lib:
        required: false
        type: string
      aux:
        required: false
        type: string


jobs:
  compile:
    runs-on: ubuntu-latest

    name: ${{ inputs.src }}-${{ inputs.platform }}-${{ inputs.version }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive 

      - name: Gather application sources 
        run: |
          echo "Creating temporary source directory"
          mkdir ${{ inputs.src }}
          echo "Including sources from test/${{ inputs.src }}"
          mv test/${{ inputs.src }}/* ${{ inputs.src }} 
          echo "Including libraries:"
          for lib in ${{ inputs.lib }}; do
            if [ -d "$lib" ]; then
              echo " - $lib/src/*"
              mv $lib/src/* ${{ inputs.src }}
            elif [ -d "lib/$lib" ]; then
              echo " - lib/$lib/src/*"
              mv lib/$lib/src/* ${{ inputs.src }}
            else
              echo " - could not find $lib, make sure the library exists"
            fi
          done
          echo "Including auxiliary resources:"
          for aux in ${{ inputs.aux }}; do
            echo " - $aux"
            mv $aux ${{ inputs.src }}
          done

      - name: Compile in cloud
        id: compile
        uses: particle-iot/compile-action@v1
        with:
          particle-access-token: ${{ secrets.PARTICLE_ACCESS_TOKEN }}
          particle-platform-name: ${{ inputs.platform }}
          device-os-version: ${{ inputs.version }}
          sources-folder: ${{ inputs.src }}

      - name: Move binary
        run: |
          mv ${{ steps.compile.outputs.firmware-path }} ${{ inputs.src }}/${{ inputs.src }}-${{ inputs.platform }}-${{ inputs.version }}.bin

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.src }}-${{ inputs.platform }}-${{ inputs.version }}
          path: ${{ inputs.src }}

      - name: Compile locally to debug
        if: ${{ failure() }}
        uses: particle-iot/compile-action@v1
        with:
          particle-platform-name: ${{ inputs.platform }}
          device-os-version: ${{ inputs.version }}
          sources-folder: ${{ inputs.src }}