# name of the job
name: Compile publish

# specify which paths to watch for changes
on:
  workflow_dispatch:  
  push:
    paths:
      - src/publish
      - LoggerCore/src
      - .github/workflows/compile.yaml
      - .github/workflows/compile-publish.yaml

# run compile via the compile.yaml
jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        # CHANGE program/lib/aux as needed
        program:
          - src: 'publish'
            lib: 'DeviceNameHelperRK FileHelperRK SequentialFileRK PublishQueueExtRK SparkFun_Qwiic_OpenLog_Arduino_Library'
            aux: 'LoggerCore/src/LoggerPlatform* LoggerCore/src/LoggerUtils* LoggerCore/src/LoggerPublisher* LoggerCore/src/LoggerSD*'
        # CHANGE platforms as needed
        platform: 
          - {name: 'photon2', version: '6.3.2'}

    # program name
    name: ${{ matrix.program.src }}-${{ matrix.platform.name }}-${{ matrix.platform.version }}

    # workflow call
    uses: ./.github/workflows/compile.yaml
    with:
      platform: ${{ matrix.platform.name }}
      version: ${{ matrix.platform.version }}
      src: ${{ matrix.program.src }}
      lib: ${{ matrix.program.lib }}
      aux: ${{ matrix.program.aux }}