name: Compile Firmware

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile application
        id: compile
        uses: particle-iot/compile-action@v1
        with:
          particle-platform-name: 'boron'
          device-os-version: '4.2.0'
          sources-folder: 'test/blink'
          particle-access-token: ${{ secrets.PARTICLE_ACCESS_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-artifact
          path: ${{ steps.compile.outputs.firmware-path }}